# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1,15 1-12 *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true
      
    - name: Clone autohome repository
      run: git clone https://github.com/swoiow/autohome.git
      
    - name: set env
      run: echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Execute Python script
      run: |
        python merge.py ./autohome/data
        python sale.py

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.csv"
        tag: ${{ env.NOW }}
        token: ${{ secrets.GITHUB_TOKEN }}
