# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1,15 1-12 *'

permissions:
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      
    - name: Clone autohome repository
      run: git clone https://github.com/swoiow/autohome.git
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Execute Python script
      run: python merge.py ./autohome/data

    - name: Generate date-based tag
      id: date-tag
      run: |
        CURRENT_DATE=$(date +'%Y-%m-%d')
        echo "::set-output name=tag::$CURRENT_DATE"
        
    - name: Create and push tag
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag ${{ steps.date-tag.outputs.tag }}
        git push origin ${{ steps.date-tag.outputs.tag }}
      
    - name: Create Release and Upload CSV files
      uses: softprops/action-gh-release@v1
      with:
        files: merged2.csv
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
